web:
        build: ./web
        volumes:
                - ./web:/home/app/webapp
        ports:
                - "80:80"
        links:
                - db
db:
        image: registry.cn-hangzhou.aliyuncs.com/qinyujia-test/mysql
        hostname: mysql-db
        environment:
                MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
                - "3306"
        volumes:
                - ./db:/var/lib/mysql
